name: movo_admin
description: Movo admin

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.0.1
  flutter_svg: ^1.0.3
  freezed_annotation: ^2.0.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  intl: ^0.17.0
  logger: ^1.1.0
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17

  common_widgets:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_widgets
  common_models:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_models
  common_utilities:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_utilities
  static_i18n:
    git:
      url: https://github.com/kume1a/flutter_static_i18n.git
  global_navigator:
    git:
      url: https://github.com/kume1a/flutter_global_navigator.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.10
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.6
  freezed: ^2.0.3
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  lint: ^1.8.2
  change_app_package_name: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
